apiVersion: v1 
kind: ConfigMap
metadata:
  name: garafana-datasources
  namespace: monitoring
data: 
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
        
        
        ]
    }